version: "3.3" 
services:
  letsencrypt:
    container_name: 'certbot-service'
    image: certbot/certbot:latest
    command: sh -c "certbot certonly --expand --webroot -w /tmp/acme_challenge -d tmdb.nestorperez.dev --text --agree-tos --email nestor@nestorperez.dev --rsa-key-size 4096 --verbose --keep-until-expiring --preferred-challenges=http"
    entrypoint: ""
    volumes:
      - letsencrypt-nestorperez-dev:/etc/letsencrypt
      - "/tmp/acme_challenge:/tmp/acme_challenge"
    environment:
      - TERM=xterm
volumes:
  letsencrypt-nestorperez-dev:
    external: true
    name: letsencrypt-nestorperez-dev
