version: "3.3"

services:
  nginx:
    container_name: 'nginx-service'
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    ports:
      - 144.126.156.147:80:80
      - 144.126.156.147:443:443
    volumes:
      - ./config:/config
      - letsencrypt-nestorperez-dev:/etc/letsencrypt:ro
      - /tmp/acme_challenge:/tmp/acme_challenge
    networks:
      - app
    restart: always
networks:
  app:
    driver: bridge

volumes:
  letsencrypt-nestorperez-dev:
    external: true
    name: letsencrypt-nestorperez-dev
